### ISSUE TITLE
Native video ads cannot be clicked after updating the SDK!

### ISSUE THREAD

**Issue by wangxing96** [fbsamples/audience-network#107]
We made a serious error after updating the Android SDK to 5.6.0.
Native video ads are highly unlikely to be clickable,  at the same time the video can play correctly.
To the opposite, picture ads work effectively.
This problem does not exist for Android SDK 5.3.2.
This problem also exists in this demo when switching Android SDK version to 5.6.0.
This bug greatly affects our advertising revenue,  please check and fix it .

**Comment by gwheet** [comment]
The bug was fixed in 5.6.1 SDK: https://developers.facebook.com/docs/audience-network/changelog-android/#5_6_1

If you are having other technical issues or experiencing bugs, please use the [bug report tool](https://www.facebook.com/business/publishersupport?hc_location=ufi) to report a bug on Audience Network.
