### ISSUE TITLE
Advanced Bidding With MoPub

### ISSUE THREAD

**Issue by billyking991** [fbsamples/audience-network#146]
I cannot proper documentation on how to initialize Facebook Audience Network with MoPub for Advanced Bidding.  I know you have to initialize FAN prior to initializing MoPub, but I can't find a code sample showing how to do it with either:

1. initializeWithSettings (How do I set up FBAdInitSettings?) or
2. initWithPlacementIDs (What is the correct String for mediationService using MoPub?) 
  
Can you please supply some Swift code detailing the proper way to do this?

Thank you for your assistance with this matter.

**Comment by onur-simsek** [comment]
Hi, 

Both of the methods (and more) are called by the 'adapter'. List of MoPub adapters for various Ad networks can be seen at the https://developers.mopub.com/publishers/mediation/integrate/ page. 

Following instructions on https://developers.mopub.com/publishers/mediation/networks/facebook/ should be sufficient for successful initialization.

**Comment by SodaSurfer** [comment]
@onur-simsek 
I'm sorry but your answer isn't satisfying.
in the page you mentioned: https://developers.mopub.com/publishers/mediation/integrate/
there is no mentioning of the string that we need to pass when initializing the FBAdInitSettings object (what is the exact string we need to pass as "mediationService" when working with Mopub?)

and the instructions in  https://developers.mopub.com/publishers/mediation/networks/facebook/  are very unclear, therefore we indeed really need an example for a correct implementation, because currently it just doesn't work (well, at least for me, I can't get the integration for Mopub and Facebook bidding to work unfortunately...)

thanks!
