### ISSUE TITLE
Crash when show interstitial

### ISSUE THREAD

**Issue by LazyBonesLZ** [fbsamples/audience-network#41]
I tested with official demo(FAN SDK v4.25.0) on my SAMSUNG Tablet, if the interstitial ad is "mp4" format,sometimes crash.
**Here is my device info**:
   Samsung SM-T710
   Android 5.0.2
   API 21
**Crash log**:
[Crash_log.txt](https://github.com/fbsamples/audience-network/files/1240687/Crash_log.txt)

**Comment by phzhou** [comment]
Hi @LazyBonesLZ there is a known issue on the SDK version 4.25, there is some cases where there is a race condition in the code which leads to this "divide by zero" crash.
This will be fixed in SDK version 4.26 which is to be published soon, or you can revert back to the more stable SDK of version 4.23 for the time being.
Thanks!
